### ISSUE TITLE
Restrict number of queries per minute(s)

### ISSUE THREAD

**Issue by juliangruendner** [medizininformatik-initiative/feasibility-backend#20]
It should be possible to configure a maximum number of queries a user can send per minute.

Two env params should be added:
app.security.nqueries.amount: ${SECURITY_NQUERIES_AMOUNT: 3}
app.security.nqueries.perminutes: ${SECURITY_NQUERIES_PERMINUTES: 1}

The endpoint:
POST query
should then be secured allowing only a maximum number of app.security.nqueries.amount per app.security.nqueries.perminutes minutes.

=> default = 3 queries per minute.

potential implementation:

As each query is posted the last queries of the user within a certain time are checked and the request rejected if the number is greater than the configured amount:

=>

```
select count(*) from query where created_at > (now() - interval '<app.security.nqueries.perminutes> min') and created_by = '<cur_user_id>';
```

If the count > app.security.nqueries.amount

the request should be rejected with status code 429 (too many requests)

**Comment by DiCanio** [comment]
Just some thoughts on this:

* Are you sure you want to do this on the application level?
Depending on the TTL of an auth token it should also be possible to move the rate limiting upstream and let a proxy handle it, e.g. use IP & Token to distinguish users from each other. NGINX and HaProxy are very much capable of doing this.

* One can also look at this from a site's point of view. They should know best what kind of throughput can be offered (depending on their infrastructure, server load etc.).
So it might make more sense to adjust the process in a way that each site is able to configure some kind of back-off threshold. The backend itself should be able to respect that and act accordingly, e.g. by enqueing further requests.

In the end all this comes down to WHY this feature is needed in the first place?
Is it because a high rate of queries causes a heavy load on some sites having a lot of data already imported to their FHIR server?
If so then I would double down on a back-off strategy.
Or is it simply a security feature to prevent users from trying to work against the obfuscation?

**Comment by juliangruendner** [comment]
> Or is it simply a security feature to prevent users from trying to work against the obfuscation?

@DiCanio  - yes - its a security feature for obfuscation hence i think its best placed at application level

**Comment by geloro94** [comment]
This is a requirement to solve a problem that we shouldn't have in the first place. Furthermore with a limit of 3 queries per min it still only takes 10 minutes on average to identify a single patient that is identifiable by patients = 6. On the other hand, we sacrifice user experience. For anyone who sends more than 3 legit queries per minute.

**Comment by DiCanio** [comment]
Rate limiting is **always** a problem as you don't want your systems to be flooded with requests.

There are simply multiple layers that this can be tackled on:
- within the load balancer (rather coarse restrictions)
- within the backend (fine-grained restrictions using heuristics and data at hand)
- within a site's process (throttle requests to avoid system pressure)

Without any of them, availability may get thrown out the window leading to actual bad user experience.

I'm with you that a user should be able to send a reasonable amount of queries per minute. Simply restricting requests on a temporal base is indeed a bit short sighted.
Maybe we can agree on a set of checks that can be implemented on an application level. Some suggestions:
- has the user already submited this query in the last XYZ (probably has the same result -> no need to run this again)
- is the same query already running (probably submitted by another user -> wait for the result)
- is the user excessively trying to narrow down criteria (potential exploit)
