### ISSUE TITLE
Only summary result returned if less (<) than x sites answered

### ISSUE THREAD

**Issue by juliangruendner** [medizininformatik-initiative/feasibility-backend#61]
Only the overall result (number of patients across all sites) should be returned from the result endpoints if the number of sites that have returned a result is less (<) a configurable amount.

=> if less x sites answered return QueryResult without resultLines.

This should be applied to all query "result" endpoints except the admin protected one which returns the un-obfuscated site names of a query.

**Comment by michael-82** [comment]
Currently we have 3 relevant endpoints here

1. GET ../query/{id} - which returns the query content and - if available - the result
2. GET ../query/{id}/result - which returns only the result, but includes the obfuscated site names
3. GET ../query/{id}/detailed - which is like 2) but does not obfuscate the site names (and is only available to admins)

However, IIRC we also need the option to just query the summary result anyways, why I would propose to include the new endpoint in this issue/pr as well. And changing the others as well where necessary (e.g. endpoint 1 is only used when loading saved queries - which needs a revamp anyways due to #58 ).

So, my suggestion would be that we will then have

1. GET ../query/{id} - which returns only the query content (which would be similar to but not the same as ../query{id}/content)
2. GET ../query/{id}/result - which returns only the result summary
3. GET ../query/{id}/with-sites - which returns only the result, but includes the obfuscated site names
4. GET ../query/{id}/detailed - which is like 2) but does not obfuscate the site names (and is only available to admins)

**Comment by michael-82** [comment]
Closed by #64
